---
#aws credentials
aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
aws_region: "us-east-1" # Replace with your desired region

#ec2 instance details
ec2_instance_type: "t2.micro"
ec2_instance_ami: "ami-0f9de6e2d2f067fca" # Amazon Linux 2 AMI
ec2_instance_key_name: "my-key-pair.pem" # Replace with your key pair name
ec2_instance_security_group: "my-wordpress-sg" # Replace with your security group name
ec2_instance_subnet_id: "subnet-0bb1c79de3EXAMPLE" # Replace with your subnet ID
assign_public_ip: true
volume_size: 8 # Size in GB
ec2_security_group_name: "wordpress-sg" # Replace with your security group name
ec2_instance_name: "wordpress-server" # Replace with your instance name

#wordpress details
wordpress_db_name: "wordpress"
wordpress_db_user: "admin"
wordpress_db_password: "password" # Replace with a strong password
wordpress_db_host: "localhost"
wordpress_db_port: 3306
wordpress_admin_user: "admin"
wordpress_admin_password: "password" # Replace with a strong password
wordpress_admin_email: "Hs6tL@example.com"

#wordpress plugins
wordpress_plugins:
  - name: "akismet"
    state: "present"
  - name: "jetpack"
    state: "present"
  - name: "wordpress-seo"
    state: "present"

#wordpress themes
wordpress_themes:
  - name: "twentytwentyone"
    state: "present" 
  - name: "astra"
    state: "present"

#wordpress settings
wordpress_settings:
  - name: "page_on_front"
    value: "page"
  - name: "show_on_front"
    value: "page"


