---
# tasks file for ec2-provision
- name: create security group
  amazon.aws.ec2_security_group:
    name: "{{ ec2_security_group_name }}"
    description: "Security group for {{ ec2_security_group_name }}"
    state: present
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: "0.0.0.0/0"
    tags:
      Name: "{{ ec2_security_group_name }}"
  register: security_group_result

- name: create ec2 instance
  amazon.aws.ec2_instance:
    name: "{{ ec2_instance_name }}"
    image_id: "{{ ec2_instance_ami }}"
    instance_type: "{{ ec2_instance_type }}"
    key_name: "{{ ec2_instance_key_name }}"
    security_groups:  # Use security group names instead of IDs
      - "{{ ec2_security_group_name }}"
    network_interfaces:  # Replace deprecated 'network' parameter
      - assign_public_ip: "{{ assign_public_ip }}"
    volumes:
      - device_name: /dev/xvda
        ebs:
          volume_size: "{{ volume_size }}"
          delete_on_termination: true
    region: "{{ aws_region }}"
    tags:
      Name: "{{ ec2_instance_name }}"
  register: ec2_instance_result

- name: wait for instance to be running
  amazon.aws.ec2_instance:
    instance_ids: "{{ ec2_instance_result.instance_ids }}"
    state: running
    wait: yes
    region: "{{ aws_region }}"

- name: get instance public IP
  amazon.aws.ec2_instance_info:
    instance_ids: "{{ ec2_instance_result.instance_ids }}"
    region: "{{ aws_region }}"
  register: ec2_instance_info

- name: set instance public IP
  set_fact:
    ec2_instance_public_ip: "{{ ec2_instance_info.instances[0].public_ip_address }}"

# add new instance to host group
- name: add new instance to host group
  add_host:
    name: "{{ ec2_instance_public_ip }}"
    groups: wordpress_servers
    ansible_ssh_private_key_file: "~/.ssh/{{ ec2_instance_key_name }}"
    ansible_user: ubuntu

#wait for instance to be reachable
- name: wait for instance to be reachable
  wait_for:
    host: "{{ ec2_instance_public_ip }}"
    port: 22
    delay: 10
    timeout: 300
    state: present