---
# tasks file for wordpress_setup
#create wordpress directory
- name: create wordpress directory
  file:
    path: /var/www/wordpress
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
# download wordpress
- name: download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
- name: extract wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/wordpress
    remote_src: true  
# remove downloaded tar file
- name: remove downloaded tar file
  file:
    path: /tmp/wordpress.tar.gz
    state: absent

- name: copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'
# set permissions for wordpress directory
- name: set permissions
  file:
    path: /var/www/wordpress
    owner: www-data
    group: www-data
    mode: '0755'  
- name: set permissions for wp-content
  file:
    path: /var/www/wordpress/wp-content
    owner: www-data
    group: www-data
    mode: '0755'  
# ensure mysql is running
- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

# set MySQL root password
- name: Set MySQL root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    state: present

# remove anonymous users
- name: Remove anonymous MySQL users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

# disallow root login remotely
- name: Disallow root login remotely
  mysql_user:
    name: root
    host: "{{ item }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop:
    - localhost
    - 127.0.0.1
    - ::1

# remove test database
- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

# reload privilege tables
- name: Reload MySQL privilege tables
  command: mysqladmin flush-privileges -u root -p"{{ mysql_root_password }}"

# create wordpress database
- name: create wordpress database
  mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
# create wordpress user
- name: create wordpress user
  mysql_user:
    name: wordpress
    password: zaq123nji987
    priv: 'wordpress.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
#