---
# tasks file for wordpress_setup
#create wordpress directory
- name: create wordpress directory
  file:
    path: /var/www/wordpress
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
# download wordpress
- name: download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
- name: extract wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/wordpress
    remote_src: true  
- name: copy wp-config.php
  copy:
    src: wp-config.php
    dest: /var/www/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'
- name: set permissions
  file:
    path: /var/www/wordpress
    owner: www-data
    group: www-data
    mode: '0755'  
- name: set permissions for wp-content
  file:
    path: /var/www/wordpress/wp-content
    owner: www-data
    group: www-data
    mode: '0755'  
# ensure mysql is running
- name: ensure mysql is running
  service:
    name: mysql
    state: started
    enabled: yes
#secure mysql installation
- name: secure mysql installation
  mysql_secure_installation:
    validate_password: no
    remove_anonymous_users: yes
    disallow_root_login_remotely: yes
    remove_test_database: yes
    reload_service: yes
    create_database: no
    root_password: "{{ mysql_root_password }}"
    root_password_confirm: "{{ mysql_root_password }}"
    state: present

# create wordpress database
- name: create wordpress database
  mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
# create wordpress user
- name: create wordpress user
  mysql_user:
    name: wordpress
    password: zaq123nji987
    priv: 'wordpress.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
# 